version: "3"
services:
  db:
    image: mysql:8.0
    container_name: userswebapi
    hostname: userswebapi
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 1600:3306
    environment:
      MYSQL_ROOT_PASSWORD: RdlqT2BZUKyos832