version: "3"
services:
  database:
    image: mysql:8.0
    container_name: simplexinvoice_db
    hostname: simplexinvoice_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: RdlqT2BZUKyos832
  # api:
  #   container_name: simplexinvoice_api
  #   hostname: simplexinvoice_api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - database
  #   ports:
  #     - "5000:80"
  #     - "5001:443"
  #   restart: always
  #   environment:    
  #     DBHOST: database
  #     ASPNETCORE_ENVIRONMENT: "Release"
  #     DOTNET_USE_POLLING_FILE_WATCHER: "true"
  #     ConnectionStrings__DefaultConnection: "server=simplexinvoice_db;Database=simplexinvoice;uid=root;Password=RdlqT2BZUKyos832;persistsecurityinfo=True;"
  #     JWTConfig_SecretKey: "asdwda1d8a4sd8w4das8d*w8d*asd@#r"
  #     CacheConfig_AbsoluteExpirationInHours: 1
  #     CacheConfig_SlidingExpirationInMinutes: 30
  #     EmailConfig_FromEmail: "example@example.com"
  #     EmailConfig_FromHost: "smtp.example.com"
  #     EmailConfig_FromPassword: "12345678"