version: "3"
services:
  db:
    image: mysql:8.0
    container_name: userswebapi
    hostname: userswebapi
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 1600:3306
    environment:
      MYSQL_ROOT_PASSWORD: RdlqT2BZUKyos832
    networks:
      - users-network
  api:
    image: dockerusersapi
    build:
      context: .
      dockerfile: src/Users.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      ConnectionStrings__DefaultConnection: "server=userswebapi;Database=users;uid=root;Password=RdlqT2BZUKyos832;persistsecurityinfo=True;"
    ports:
      - "21440:80"
      - "44540:443"
    networks:
      - users-network
  angular:    
    build: 
      context: .
      dockerfile: clients/UsersAngular/Dockerfile
    ports:
      - 4201:80
    networks:
      - users-network
networks:
  users-network:
    driver: bridge