export class InvoiceLineDto {
    id: string = '';
    invoiceId: string = '';
    lineNumber: string = '';
    productCode: string = '';
    productName: string = '';
    productDescription: string = '';
    packages: number = 0;
    quantity: number = 0;
    price: number = 0;
    currency: string = '';
    taxName: string = '';
    taxRate: number = 0;
    discountRate: number = 0;
    tax: number = 0;
    discount: number = 0;
    taxBase: number = 0;
    total: number = 0;
}